services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "127.0.0.1:3004:3004"
    volumes:
      - type: bind
        source: .dev.vars
        target: /app/.dev.vars
        read_only: true
    environment:
      - NODE_ENV=development
    env_file:
      - .env
